<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0-windows10.0.17763.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWPF>true</UseWPF>
		<UseWindowsForms>true</UseWindowsForms>
		<ApplicationIcon>assets\logo.ico</ApplicationIcon>
		<SupportedOSPlatformVersion>10.0.17763.0</SupportedOSPlatformVersion>
		<FileVersion>2.0.5</FileVersion>
	</PropertyGroup>

	<ItemGroup>
	  <None Remove="assets\discord.png" />
	  <None Remove="assets\github.png" />
	  <None Remove="assets\logo.png" />
	</ItemGroup>

	<ItemGroup>
	  <Content Include="bin\Release\net10.0-windows\publish\win-x64\CrosshairY.deps.json" />
	  <Content Include="bin\Release\net10.0-windows\publish\win-x64\CrosshairY.runtimeconfig.json" />
	</ItemGroup>

	<ItemGroup>
	  <None Include="bin\Release\net10.0-windows\publish\win-x64\ColorPicker.dll" />
	  <None Include="bin\Release\net10.0-windows\publish\win-x64\ColorPicker.Models.dll" />
	  <None Include="bin\Release\net10.0-windows\publish\win-x64\CrosshairY.dll" />
	  <None Include="bin\Release\net10.0-windows\publish\win-x64\CrosshairY.dll.config" />
	  <None Include="bin\Release\net10.0-windows\publish\win-x64\CrosshairY.exe" />
	  <None Include="bin\Release\net10.0-windows\publish\win-x64\CrosshairY.pdb" />
	  <None Include="bin\Release\net10.0-windows\publish\win-x64\Hardcodet.NotifyIcon.Wpf.dll" />
	  <None Include="bin\Release\net10.0-windows\publish\win-x64\MahApps.Metro.IconPacks.BootstrapIcons.dll" />
	  <None Include="bin\Release\net10.0-windows\publish\win-x64\MahApps.Metro.IconPacks.BoxIcons.dll" />
	  <None Include="bin\Release\net10.0-windows\publish\win-x64\MahApps.Metro.IconPacks.BoxIcons2.dll" />
	  <None Include="bin\Release\net10.0-windows\publish\win-x64\MahApps.Metro.IconPacks.CircumIcons.dll" />
	  <None Include="bin\Release\net10.0-windows\publish\win-x64\MahApps.Metro.IconPacks.Codicons.dll" />
	  <None Include="bin\Release\net10.0-windows\publish\win-x64\MahApps.Metro.IconPacks.Coolicons.dll" />
	  <None Include="bin\Release\net10.0-windows\publish\win-x64\MahApps.Metro.IconPacks.Core.dll" />
	  <None Include="bin\Release\net10.0-windows\publish\win-x64\MahApps.Metro.IconPacks.dll" />
	  <None Include="bin\Release\net10.0-windows\publish\win-x64\MahApps.Metro.IconPacks.Entypo.dll" />
	  <None Include="bin\Release\net10.0-windows\publish\win-x64\MahApps.Metro.IconPacks.EvaIcons.dll" />
	  <None Include="bin\Release\net10.0-windows\publish\win-x64\MahApps.Metro.IconPacks.FeatherIcons.dll" />
	  <None Include="bin\Release\net10.0-windows\publish\win-x64\MahApps.Metro.IconPacks.FileIcons.dll" />
	  <None Include="bin\Release\net10.0-windows\publish\win-x64\MahApps.Metro.IconPacks.Fontaudio.dll" />
	  <None Include="bin\Release\net10.0-windows\publish\win-x64\MahApps.Metro.IconPacks.FontAwesome.dll" />
	  <None Include="bin\Release\net10.0-windows\publish\win-x64\MahApps.Metro.IconPacks.FontAwesome5.dll" />
	  <None Include="bin\Release\net10.0-windows\publish\win-x64\MahApps.Metro.IconPacks.FontAwesome6.dll" />
	  <None Include="bin\Release\net10.0-windows\publish\win-x64\MahApps.Metro.IconPacks.Fontisto.dll" />
	  <None Include="bin\Release\net10.0-windows\publish\win-x64\MahApps.Metro.IconPacks.ForkAwesome.dll" />
	  <None Include="bin\Release\net10.0-windows\publish\win-x64\MahApps.Metro.IconPacks.GameIcons.dll" />
	  <None Include="bin\Release\net10.0-windows\publish\win-x64\MahApps.Metro.IconPacks.Ionicons.dll" />
	  <None Include="bin\Release\net10.0-windows\publish\win-x64\MahApps.Metro.IconPacks.JamIcons.dll" />
	  <None Include="bin\Release\net10.0-windows\publish\win-x64\MahApps.Metro.IconPacks.KeyruneIcons.dll" />
	  <None Include="bin\Release\net10.0-windows\publish\win-x64\MahApps.Metro.IconPacks.Lucide.dll" />
	  <None Include="bin\Release\net10.0-windows\publish\win-x64\MahApps.Metro.IconPacks.Material.dll" />
	  <None Include="bin\Release\net10.0-windows\publish\win-x64\MahApps.Metro.IconPacks.MaterialDesign.dll" />
	  <None Include="bin\Release\net10.0-windows\publish\win-x64\MahApps.Metro.IconPacks.MaterialLight.dll" />
	  <None Include="bin\Release\net10.0-windows\publish\win-x64\MahApps.Metro.IconPacks.MemoryIcons.dll" />
	  <None Include="bin\Release\net10.0-windows\publish\win-x64\MahApps.Metro.IconPacks.Microns.dll" />
	  <None Include="bin\Release\net10.0-windows\publish\win-x64\MahApps.Metro.IconPacks.MingCuteIcons.dll" />
	  <None Include="bin\Release\net10.0-windows\publish\win-x64\MahApps.Metro.IconPacks.Modern.dll" />
	  <None Include="bin\Release\net10.0-windows\publish\win-x64\MahApps.Metro.IconPacks.MynaUIIcons.dll" />
	  <None Include="bin\Release\net10.0-windows\publish\win-x64\MahApps.Metro.IconPacks.Octicons.dll" />
	  <None Include="bin\Release\net10.0-windows\publish\win-x64\MahApps.Metro.IconPacks.PhosphorIcons.dll" />
	  <None Include="bin\Release\net10.0-windows\publish\win-x64\MahApps.Metro.IconPacks.PicolIcons.dll" />
	  <None Include="bin\Release\net10.0-windows\publish\win-x64\MahApps.Metro.IconPacks.PixelartIcons.dll" />
	  <None Include="bin\Release\net10.0-windows\publish\win-x64\MahApps.Metro.IconPacks.RadixIcons.dll" />
	  <None Include="bin\Release\net10.0-windows\publish\win-x64\MahApps.Metro.IconPacks.RemixIcon.dll" />
	  <None Include="bin\Release\net10.0-windows\publish\win-x64\MahApps.Metro.IconPacks.RPGAwesome.dll" />
	  <None Include="bin\Release\net10.0-windows\publish\win-x64\MahApps.Metro.IconPacks.SimpleIcons.dll" />
	  <None Include="bin\Release\net10.0-windows\publish\win-x64\MahApps.Metro.IconPacks.Typicons.dll" />
	  <None Include="bin\Release\net10.0-windows\publish\win-x64\MahApps.Metro.IconPacks.Unicons.dll" />
	  <None Include="bin\Release\net10.0-windows\publish\win-x64\MahApps.Metro.IconPacks.VaadinIcons.dll" />
	  <None Include="bin\Release\net10.0-windows\publish\win-x64\MahApps.Metro.IconPacks.WeatherIcons.dll" />
	  <None Include="bin\Release\net10.0-windows\publish\win-x64\MahApps.Metro.IconPacks.Zondicons.dll" />
	  <None Include="bin\Release\net10.0-windows\publish\win-x64\Microsoft.Toolkit.Uwp.Notifications.dll" />
	  <None Include="bin\Release\net10.0-windows\publish\win-x64\Microsoft.Windows.SDK.NET.dll" />
	  <None Include="bin\Release\net10.0-windows\publish\win-x64\Microsoft.Xaml.Behaviors.dll" />
	  <None Include="bin\Release\net10.0-windows\publish\win-x64\WinRT.Runtime.dll" />
	</ItemGroup>

	<ItemGroup>
		<Resource Include="assets\discord.png" />
		<Resource Include="assets\github.png" />
		<Resource Include="assets\logo.ico" />
	</ItemGroup>
	
	<ItemGroup>
		<PackageReference Include="Hardcodet.NotifyIcon.Wpf" Version="2.0.1" />
		<PackageReference Include="MahApps.Metro.IconPacks" Version="6.2.1" />
		<PackageReference Include="Microsoft.Toolkit.Uwp.Notifications" Version="7.1.3" />
		<PackageReference Include="PixiEditor.ColorPicker" Version="3.4.2.3" />
	</ItemGroup>

	<ItemGroup>
	  <Resource Include="assets\logo.png" />
	</ItemGroup>

</Project>